// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMoUXCzQzOsLZNkNVf4nLBVZX3UJJDgY4',
    appId: '1:695362025015:web:ce17060e01eab39fcbb1b2',
    messagingSenderId: '695362025015',
    projectId: 'flutter-learning-6473d',
    authDomain: 'flutter-learning-6473d.firebaseapp.com',
    storageBucket: 'flutter-learning-6473d.firebasestorage.app',
    measurementId: 'G-S58W3PYHGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtIr1qRlh3UzXlecAejamw4Cdwhj2vCE',
    appId: '1:695362025015:android:90dd4b5091468a8ccbb1b2',
    messagingSenderId: '695362025015',
    projectId: 'flutter-learning-6473d',
    storageBucket: 'flutter-learning-6473d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAl0t819FNzHlIb5YotRilCgly4hSwDVs',
    appId: '1:695362025015:ios:f8b31d077be28083cbb1b2',
    messagingSenderId: '695362025015',
    projectId: 'flutter-learning-6473d',
    storageBucket: 'flutter-learning-6473d.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAl0t819FNzHlIb5YotRilCgly4hSwDVs',
    appId: '1:695362025015:ios:f8b31d077be28083cbb1b2',
    messagingSenderId: '695362025015',
    projectId: 'flutter-learning-6473d',
    storageBucket: 'flutter-learning-6473d.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMoUXCzQzOsLZNkNVf4nLBVZX3UJJDgY4',
    appId: '1:695362025015:web:0c65f87bb274c2b5cbb1b2',
    messagingSenderId: '695362025015',
    projectId: 'flutter-learning-6473d',
    authDomain: 'flutter-learning-6473d.firebaseapp.com',
    storageBucket: 'flutter-learning-6473d.firebasestorage.app',
    measurementId: 'G-MEY19GJ6KK',
  );
}
